COURSES = [
    {
        "id": "html-css-foundations", "title": "HTML & CSS Foundations", "category": "Web", "level": "Beginner",
        "hours": 12, "rating": 4.8, "students": 5230, "price": 349, "instructor": "Thandi Mokoena",
        "short": "Build and style your first responsive web pages.",
        "description": "Start from a blank file and finish with a live portfolio page. You will learn how the web is structured, how to style it with modern CSS, and how to make it look great on any screen.",
        "modules": ["Your first HTML page", "Semantic structure", "Styling with CSS", "Flexbox and Grid", "Responsive design", "Project: personal portfolio"],
    },
    {
        "id": "javascript-essentials", "title": "JavaScript Essentials", "category": "Web", "level": "Beginner",
        "hours": 16, "rating": 4.7, "students": 4810, "price": 449, "instructor": "Kabelo Dlamini",
        "short": "Make pages interactive with variables, functions and the DOM.",
        "description": "Learn the language of the web by building small interactive projects. Covers the core syntax, working with the DOM, events, and fetching data from APIs.",
        "modules": ["Values and variables", "Functions", "Arrays and objects", "The DOM", "Events", "Fetching data", "Project: quiz app"],
    },
    {
        "id": "react-from-scratch", "title": "React from Scratch", "category": "Web", "level": "Intermediate",
        "hours": 20, "rating": 4.8, "students": 3120, "price": 649, "instructor": "Aisha Patel",
        "short": "Components, state and hooks — build a real single-page app.",
        "description": "Go from JavaScript to modern front-end development. You will think in components, manage state with hooks, and ship a complete app with routing.",
        "modules": ["Thinking in components", "Props and state", "Hooks in depth", "Forms", "Routing", "Data fetching", "Project: task manager"],
    },
    {
        "id": "python-for-beginners", "title": "Python for Beginners", "category": "Data", "level": "Beginner",
        "hours": 14, "rating": 4.9, "students": 6420, "price": 399, "instructor": "Sipho Nkosi",
        "short": "The friendliest first language — logic, loops and little programs.",
        "description": "No experience needed. Write real Python from lesson one and finish by automating a boring task from your own life.",
        "modules": ["Hello, Python", "Decisions and loops", "Lists and dictionaries", "Functions", "Files", "Project: automate a task"],
    },
    {
        "id": "data-analysis-python", "title": "Data Analysis with Python", "category": "Data", "level": "Intermediate",
        "hours": 18, "rating": 4.6, "students": 2740, "price": 599, "instructor": "Lerato Khumalo",
        "short": "Clean, explore and chart real datasets with pandas.",
        "description": "Turn messy spreadsheets into insight. Load, clean and analyse data with pandas, then tell the story with clear charts.",
        "modules": ["Notebooks and pandas", "Cleaning data", "Grouping and joining", "Visualisation", "Statistics basics", "Project: analyse a dataset"],
    },
    {
        "id": "sql-databases", "title": "SQL & Databases", "category": "Data", "level": "Beginner",
        "hours": 10, "rating": 4.7, "students": 3890, "price": 349, "instructor": "Johan van Wyk",
        "short": "Query, join and design relational databases.",
        "description": "Every app needs data. Learn to write confident SQL queries and design tables that stay tidy as your project grows.",
        "modules": ["Tables and rows", "SELECT and WHERE", "Joins", "Aggregates", "Designing schemas", "Project: library database"],
    },
    {
        "id": "linear-algebra-programmers", "title": "Linear Algebra for Programmers", "category": "CS Fundamentals", "level": "Intermediate",
        "hours": 15, "rating": 4.5, "students": 1980, "price": 499, "instructor": "Dr. Naledi Mahlangu",
        "short": "Vectors, matrices and transformations — explained with code.",
        "description": "The maths behind graphics, games and machine learning, taught through code you can run. Every concept is paired with a visual and a small program.",
        "modules": ["Vectors", "Matrices", "Transformations", "Systems of equations", "Eigenvectors", "Project: 2D graphics engine"],
    },
    {
        "id": "data-structures-algorithms", "title": "Data Structures & Algorithms", "category": "CS Fundamentals", "level": "Advanced",
        "hours": 24, "rating": 4.7, "students": 2410, "price": 749, "instructor": "Prof. Ravi Govender",
        "short": "Lists, trees, graphs and the algorithms that power them.",
        "description": "Build the toolkit that technical interviews and real systems rely on. Implement each structure yourself and learn how to reason about performance.",
        "modules": ["Big-O thinking", "Arrays and linked lists", "Stacks and queues", "Trees", "Graphs", "Sorting and searching", "Dynamic programming", "Project: route planner"],
    },
    {
        "id": "intro-machine-learning", "title": "Intro to Machine Learning", "category": "AI", "level": "Intermediate",
        "hours": 22, "rating": 4.6, "students": 2950, "price": 699, "instructor": "Zanele Mthembu",
        "short": "Train your first models and learn how to evaluate them.",
        "description": "Understand what machine learning really is, train regression and classification models, and learn how to tell a good model from a lucky one.",
        "modules": ["What is ML?", "Regression", "Classification", "Evaluating models", "Overfitting", "Project: predict house prices"],
    },
    {
        "id": "building-with-llm-apis", "title": "Building with LLM APIs", "category": "AI", "level": "Advanced",
        "hours": 12, "rating": 4.8, "students": 1760, "price": 799, "instructor": "Michael Botha",
        "short": "Prompting, tool use and shipping AI features safely.",
        "description": "Add large-language-model features to real products. Covers prompt design, structured output, tool use, evaluation and responsible deployment.",
        "modules": ["How LLMs work", "Prompt design", "Structured output", "Tool use", "Evaluation", "Project: study-buddy chatbot"],
    },
    {
        "id": "flutter-mobile-apps", "title": "Flutter Mobile Apps", "category": "Mobile", "level": "Intermediate",
        "hours": 19, "rating": 4.6, "students": 2130, "price": 649, "instructor": "Busi Ndlovu",
        "short": "One codebase, beautiful apps on Android and iOS.",
        "description": "Learn Dart and Flutter by building a polished mobile app, from layout and navigation to state management and publishing.",
        "modules": ["Dart basics", "Widgets", "Layouts", "Navigation", "State management", "Project: habit tracker"],
    },
    {
        "id": "git-github-workflow", "title": "Git & GitHub Workflow", "category": "Tools", "level": "Beginner",
        "hours": 6, "rating": 4.9, "students": 5670, "price": 199, "instructor": "Kabelo Dlamini",
        "short": "Version control and teamwork without the panic.",
        "description": "Commit, branch, merge and collaborate like a professional team. Short, practical and the best first step for any group project.",
        "modules": ["Why version control", "Commits", "Branches", "Merging and conflicts", "Pull requests"],
    },
]
